"use strict";
exports.__esModule = true;
var mueble_controller_1 = require("../controllers/mueble.controller");
var express_1 = require("express");
var router = express_1["default"].Router();
router.get('/', mueble_controller_1.getBuscarMueble);
router.get('/:id', mueble_controller_1.getMueblePorId);
router.get('/usuariosAsigandosMueble/:id', mueble_controller_1.getUsuariosAsignadosMueble);
router.get('/materiasPrimasAsigandosMueble/:id', mueble_controller_1.getMateriasPrimasAsignadosMueble);
router.post('/', mueble_controller_1.postInsertarMueble);
router.post('/listados', mueble_controller_1.postInsertarMuebleListados);
router.put('/', mueble_controller_1.putActualizarMueble);
router["delete"]('/:id', mueble_controller_1.deleteMueblePorId);
exports["default"] = router;
