"use strict";
exports.__esModule = true;
var express_1 = require("express");
var permiso_controller_1 = require("../controllers/permiso.controller");
var router = express_1["default"].Router();
router.get('/', permiso_controller_1.getPermiso);
router.get('/:id', permiso_controller_1.getPermisoPorId);
router.post('/', permiso_controller_1.postInsertarPermiso);
router.put('/', permiso_controller_1.putActualizarPermiso);
router["delete"]('/:id', permiso_controller_1.deleteEliminarPermiso);
exports["default"] = router;
