"use strict";
exports.__esModule = true;
var venta_controller_1 = require("../controllers/venta.controller");
var express_1 = require("express");
var router = express_1["default"].Router();
router.get('/', venta_controller_1.getVenta);
router.get('/mueblesVentas', venta_controller_1.getMueblesParaVentas);
router.get('/:id', venta_controller_1.getbuscarVentaPorId);
router.post('/', venta_controller_1.postInsertarVenta);
router.post('/listados', venta_controller_1.postInsertarVentaMueble);
router.put('/', venta_controller_1.putActualizarVenta);
router["delete"]('/:id', venta_controller_1.deleteVentaPorId);
exports["default"] = router;
